## ARTIFICIAL NEURAL NETWORKS

## 1. Data Exploration and Preprocessing

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
data= pd.read_csv(r"C:\Users\sai\OneDrive\Desktop\Alphabets_data.csv")
data.head()

,letter,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
0,T,2,8,3,5,1,8,13,0,6,6,10,8,0,8,0,8
1,I,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
2,D,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9
3,N,7,11,6,6,3,5,9,4,6,4,4,10,6,10,2,8
4,G,2,1,3,1,1,8,6,6,6,6,5,9,1,7,5,10

In [7]:
data.shape

(20000, 17)

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   letter  20000 non-null  object
 1   xbox    20000 non-null  int64
 2   ybox    20000 non-null  int64
 3   width   20000 non-null  int64
 4   height  20000 non-null  int64
 5   onpix   20000 non-null  int64
 6   xbar    20000 non-null  int64
 7   ybar    20000 non-null  int64
 8   x2bar   20000 non-null  int64
 9   y2bar   20000 non-null  int64
 10  xybar   20000 non-null  int64
 11  x2ybar  20000 non-null  int64
 12  xy2bar  20000 non-null  int64
 13  xedge   20000 non-null  int64
 14  xedgey  20000 non-null  int64
 15  yedge   20000 non-null  int64
 16  yedgex  20000 non-null  int64
dtypes: int64(16), object(1)
memory usage: 2.6+ MB

In [11]:
data.describe()

,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
count,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000
mean,4.023550,7.035500,5.121850,5.37245,3.505850,6.897600,7.500450,4.628600,5.178650,8.282050,6.45400,7.929000,3.046100,8.338850,3.691750,7.80120
std,1.913212,3.304555,2.014573,2.26139,2.190458,2.026035,2.325354,2.699968,2.380823,2.488475,2.63107,2.080619,2.332541,1.546722,2.567073,1.61747
min,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,3.000000,5.000000,4.000000,4.00000,2.000000,6.000000,6.000000,3.000000,4.000000,7.000000,5.00000,7.000000,1.000000,8.000000,2.000000,7.00000
50%,4.000000,7.000000,5.000000,6.00000,3.000000,7.000000,7.000000,4.000000,5.000000,8.000000,6.00000,8.000000,3.000000,8.000000,3.000000,8.00000
75%,5.000000,9.000000,6.000000,7.00000,5.000000,8.000000,9.000000,6.000000,7.000000,10.000000,8.00000,9.000000,4.000000,9.000000,5.000000,9.00000
max,15.000000,15.000000,15.000000,15.00000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.00000,15.000000,15.000000,15.000000,15.000000,15.00000

In [13]:
#checking for missing value
missing_values = data.isnull().sum()

In [17]:
#check for duplicates
data.duplicated().sum()

1332

In [19]:
#remove duplicate data
data = data.drop_duplicates()

In [21]:
data.duplicated().sum()

0

In [23]:
data['letter'].unique()

array(['T', 'I', 'D', 'N', 'G', 'S', 'B', 'A', 'J', 'M', 'X', 'O', 'R',
       'F', 'C', 'H', 'W', 'L', 'P', 'E', 'V', 'Y', 'Q', 'U', 'K', 'Z'],
      dtype=object)

In [25]:
from sklearn.preprocessing import MinMaxScaler

x = data.drop(columns=['letter'])
y = data['letter']

#mimax scaler
scaler = MinMaxScaler()
x_scaled = scaler.fit_transform(x)

In [27]:
from sklearn.preprocessing import OneHotEncoder

# One-hot encode the target variable
encoder = OneHotEncoder()
y_en = encoder.fit_transform(y.values.reshape(-1, 1))
y_encoded = pd.DataFrame(y_en.toarray())

In [29]:
y_encoded

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18663,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
18664,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18665,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18666,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
18667,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [31]:
from sklearn.model_selection import train_test_split

# split into train and test
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y_encoded, test_size=0.2, random_state=42)

In [33]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [34]:
model1 = Sequential([
    Dense(12, activation='relu', input_shape=(x_train.shape[1],)),
    Dense(26, activation='softmax')
])

# since its a multiclass classification problem so im using relu for hidden layer and softmax for output layer

C:\Users\sai\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [37]:
model1.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
#I'm using adam optimizer bcz it uses both adagrad and rmsprop properties

In [39]:
training = model1.fit(x_train, y_encoded, epochs=20, batch_size=20, validation_split=0.2)

Epoch 1/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.0381 - loss: 3.2631 - val_accuracy: 0.0368 - val_loss: 3.2578
Epoch 2/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0405 - loss: 3.2567 - val_accuracy: 0.0368 - val_loss: 3.2575
Epoch 3/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0411 - loss: 3.2558 - val_accuracy: 0.0405 - val_loss: 3.2572
Epoch 4/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0420 - loss: 3.2541 - val_accuracy: 0.0405 - val_loss: 3.2572
Epoch 5/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0424 - loss: 3.2549 - val_accuracy: 0.0395 - val_loss: 3.2576
Epoch 6/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0461 - loss: 3.2545 - val_accuracy: 0.0368 - val_loss: 3.2569
Epoch 7/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0433 - loss: 3.2545 - val_accuracy: 0.0382 - val_loss: 3.2575
Epoch 8/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0454 - loss: 3.2540 - val_accuracy: 0.0412 - val_loss: 3.2575
Epoch 9/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0423 - loss: 3.2540 - val_accuracy: 0.0385 - val_loss: 3.2577
Epoch 10/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0510 - loss: 3.2518 - val_accuracy: 0.0412 - val_loss: 3.2583
Epoch 11/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0447 - loss: 3.2526 - val_accuracy: 0.0398 - val_loss: 3.2586
Epoch 12/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0421 - loss: 3.2536 - val_accuracy: 0.0372 - val_loss: 3.2591
Epoch 13/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0448 - loss: 3.2503 - val_accuracy: 0.0395 - val_loss: 3.2578
Epoch 14/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0469 - loss: 3.2499 - val_accuracy: 0.0382 - val_loss: 3.2583
Epoch 15/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0465 - loss: 3.2502 - val_accuracy: 0.0388 - val_loss: 3.2580
Epoch 16/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0486 - loss: 3.2502 - val_accuracy: 0.0405 - val_loss: 3.2584
Epoch 17/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0502 - loss: 3.2508 - val_accuracy: 0.0395 - val_loss: 3.2590
Epoch 18/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0477 - loss: 3.2480 - val_accuracy: 0.0368 - val_loss: 3.2589
Epoch 19/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0468 - loss: 3.2493 - val_accuracy: 0.0382 - val_loss: 3.2594
Epoch 20/20
598/598 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0474 - loss: 3.2502 - val_accuracy: 0.0372 - val_loss: 3.2602

In [40]:
model2 = Sequential([
    Dense(56, activation='relu', input_shape=(x_train.shape[1],)),
    Dense(26, activation='sigmoid')
])
model2.compile(optimizer='RMSprop', loss='categorical_crossentropy', metrics=['accuracy'])
training = model2.fit(x_train, y_encoded, epochs=20, batch_size=42, validation_split=0.2)

Epoch 1/20

C:\Users\sai\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

285/285 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0380 - loss: 3.2698 - val_accuracy: 0.0385 - val_loss: 3.2634
Epoch 2/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0451 - loss: 3.2592 - val_accuracy: 0.0435 - val_loss: 3.2599
Epoch 3/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0473 - loss: 3.2572 - val_accuracy: 0.0382 - val_loss: 3.2610
Epoch 4/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0435 - loss: 3.2568 - val_accuracy: 0.0408 - val_loss: 3.2606
Epoch 5/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0452 - loss: 3.2540 - val_accuracy: 0.0362 - val_loss: 3.2603
Epoch 6/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0475 - loss: 3.2537 - val_accuracy: 0.0362 - val_loss: 3.2607
Epoch 7/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0468 - loss: 3.2502 - val_accuracy: 0.0388 - val_loss: 3.2607
Epoch 8/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0476 - loss: 3.2516 - val_accuracy: 0.0408 - val_loss: 3.2615
Epoch 9/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0489 - loss: 3.2507 - val_accuracy: 0.0362 - val_loss: 3.2616
Epoch 10/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0458 - loss: 3.2497 - val_accuracy: 0.0408 - val_loss: 3.2618
Epoch 11/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0481 - loss: 3.2491 - val_accuracy: 0.0352 - val_loss: 3.2613
Epoch 12/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0475 - loss: 3.2494 - val_accuracy: 0.0418 - val_loss: 3.2625
Epoch 13/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0480 - loss: 3.2490 - val_accuracy: 0.0362 - val_loss: 3.2623
Epoch 14/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0505 - loss: 3.2471 - val_accuracy: 0.0345 - val_loss: 3.2629
Epoch 15/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0531 - loss: 3.2457 - val_accuracy: 0.0445 - val_loss: 3.2637
Epoch 16/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0510 - loss: 3.2464 - val_accuracy: 0.0412 - val_loss: 3.2627
Epoch 17/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0522 - loss: 3.2457 - val_accuracy: 0.0392 - val_loss: 3.2628
Epoch 18/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0529 - loss: 3.2423 - val_accuracy: 0.0368 - val_loss: 3.2630
Epoch 19/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0526 - loss: 3.2444 - val_accuracy: 0.0388 - val_loss: 3.2614
Epoch 20/20
285/285 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0517 - loss: 3.2451 - val_accuracy: 0.0362 - val_loss: 3.2636

In [ ]:
model3 = Sequential([
    Dense(56, activation='elu', input_shape=(x_train.shape[1],)),
    Dense(26, activation='sigmoid')
])
model3.compile(optimizer='RMSprop', loss='categorical_crossentropy', metrics=['accuracy'])
training = model3.fit(x_train, y_encoded, epochs=20, batch_size=42, validation_split=0.2)

Epoch 1/20

C:\Users\sai\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

263/285 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0356 - loss: 3.2752

In [ ]:
model4 = Sequential([
    Dense(56, activation='tanh', input_shape=(x_train.shape[1],)),
    Dense(26, activation='sigmoid')
])
model4.compile(optimizer='ADAgrad', loss='categorical_crossentropy', metrics=['accuracy'])
training = model4.fit(x_train, y_encoded, epochs=20, batch_size=42, validation_split=0.2)

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import numpy as np
# Get the true labels
y_true = np.argmax(y_test, axis=1)

# Get the predicted labels
y_pred = np.argmax(model1.predict(x_test), axis=1)

accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, average='weighted')
recall = recall_score(y_true, y_pred, average='weighted')
f1 = f1_score(y_true, y_pred, average='weighted')
conf_matrix = confusion_matrix(y_true, y_pred)

print("Model with relu , softmax and adam optimizer ")
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-score: {f1}")